### PR TITLE
Switch from child_process.exec to child_process.spawn to overcome buffer limits

### PR DESCRIPTION
**Pull request by ryan953**
Calling `flow status --json` can generate a large json payload. It's size depends on the number and size of files in your project. This payload was being fed into a small buffer by child_process.exec which had only a 200kb limit. See the docs here  https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback and `maxBuffer`.

To get around this we could hard-code a much higher buffer limit, but this would be arbitrary and some other project would eventually hit the boundary. To avoid that I've used `child_process.spawn` and collected the data chunks manually. This means we can use all the free memory on the system to suck up whatever `flow` tells us. I tested this against a large flow project that was (mis)configured to spew 23MB of json errors and warnings.

### CODE REVIEW

**Comment by rpl** [comment]
@ryan953 I totally agree: the default `maxBuffer` limit is not going to work on larger projects.

In an experimental branch I was redirecting the output in a file as a temporary workaround, but it was more helpful as a debugging feature than as the final solution to the `maxBuffer` limit.

This pull request was a great opportunity to look at it again and find an actual solution, and so I took a look to the changes in this pull request and to the nodejs sources for the `exec` function (e.g. https://github.com/nodejs/node/blob/master/lib/child_process.js#L195 and https://github.com/nodejs/node/blob/master/lib/child_process.js#L263), and it seems that if we set `maxBuffer` to `Infinity`, then our `exec` should behave mostly like the `spawn` function in this branch.

The combination of:

- collecting the coverage data sequentially
- setting the `maxBuffer` to `Infinity` and a reasonable default `timeout` (currently 15s by default) in the `exec` options
- tollerate flow command errors (e.g. flow command timeout or flow coverage json errors produced on the stderr, which are pretty rare but I've met it once)
- highligh in the reports the files with errors (flow command timeout, coverage json errors etc.)
- being able to exclude glob patterns (so that we can exclude problematic and non wanted files without using too many `-i` options)

seems to be enough to be able to create the flow coverage report on pretty large projects.

it would be awesome if you could test if this approach (as included in #10) works on your projects as well, I'd really like to be sure that the new strategy is going to work for you before releasing it as the new 0.2.0 version.

And thanks a lot! you helped a lot on this area!

As additional side notes related to the flow coverage command timeout:

By playing a bit around this on a project where I experienced interesting issues with the flow daemon behavior, I've noticed that if you try to collect coverage data on a file that wasn't supposed to be submitted to flow (e.g. a big minified or bundled file), then the flow daemon tries to complete the coverage collection on it, but it allocates so much memory and uses so much cpu cycles that the machine (even a very powerfull one) get stuck indefinitely.

By setting a timeout on the flow coverage command (the current default that I set is 15 seconds, and it seems to be much more of the actual time needed to collect the coverage data from a sane file), when the command that has submitted the file that is blocking the flow daemon will give up because of the timeout, the flow daemon becomes responsive again (but it doesn't release most of the memory that has been already allocated :-(, until stopped explicitly).

**Comment by ryan953** [comment]
@rpl I saw that `Infinity` value in the 0.2.0 and thought it was great, because duh `<number>` type.

I'll grab the PR for 0.2.0 and see what happens when a big project spews lots of errors.

**Comment by ryan953** [comment]
I inserted 389 errors into my project and re-ran the #10 dev/0-2-0 branch. It looks like it can handle the 400kb of json as expected. I think the `Infinity` value is going to be fine for most well-behaved projects.

**Comment by rpl** [comment]
Fix released as part of v.0.2.0

Thanks @ryan953 for the help on tracking down the issue and testing the released fix!

**Pull request closed without merging**
