### PR TITLE
fix: Added support for the new flow annotations (strict and strict-local)

### PR DESCRIPTION
**Pull request by rpl**
This PR contains the changes from #150 rebased on top of the current master tip, with some small refactorings (as agreed in https://github.com/rpl/flow-coverage-report/pull/150#discussion_r190037717) and some additions and tweaks to the tests (and updates on the related jest snapshots). 

TODO:
- [ ] fix regression with renamed config option names (keep backward compatibility and log a working before releasing this change)

### CODE REVIEW

**Comment by rpl** [comment]
@zeorin I've tried this PR locally a bit (by changing the flow annotation on some files to check that the behavior was the one I was expecting, which isn't actually much more than what is already tested in the automated tests :-P)

do you mind to try it locally on the project where you first met this issue? 
(just to double-check that everything is working correctly for you, once this is merged and the new version of the npm package released).

Thanks again for your help on this!

**Comment by zeorin** [comment]
@rpl This works for me!

BTW the warnings about the renamed config options never showed on the console, there's a `UsageError` raised instead:

```
Unexpected exception: UsageError: ERROR: No glob has been specified. UsageError: ERROR: No glob has been specified.
    at new UsageError (/home/zeorin/code/my-framework/node_modules/flow-coverage-report/dist/lib/cli/config.js:51:124)
    at validateConfig (/home/zeorin/code/my-framework/node_modules/flow-coverage-report/dist/lib/cli/config.js:271:11)
    at Object.exports.run (/home/zeorin/code/my-framework/node_modules/flow-coverage-report/dist/lib/cli/index.js:28:32)
    at Object.<anonymous> (/home/zeorin/code/my-framework/node_modules/flow-coverage-report/bin/flow-coverage-report.js:4:50)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```
The readme in your branch hasn't been updated to reflect the new option names yet either. I read the source to adjust my config and once that was done it works just fine:
```
┌──────────┬─────────────┬─────────┬───────┬─────────┬───────────┐
│ filename │  annotation │ percent │ total │ covered │ uncovered │
│ index.js │ flow strict │   100 % │    10 │      10 │ 0         │
└──────────┴─────────────┴─────────┴───────┴─────────┴───────────┘
┌─────────────────────────┬──────────────────────────────────────────┐
│ included glob patterns: │ **/*.js?(x)                              │
│ excluded glob patterns: │ node_modules/**, **/_book/**             │
│              threshold: │ 100                                      │
│       concurrent files: │ 4                                        │
│           generated at: │ Sat May 26 2018 22:27:25 GMT+0200 (SAST) │
│           flow version: │ 0.73.0                                   │
│      flow check passed: │ yes (0 errors)                           │
└─────────────────────────┴──────────────────────────────────────────┘
┌──────────────┬─────────┬───────┬─────────┬───────────┐
│ project      │ percent │ total │ covered │ uncovered │
│ my-framework │   100 % │    10 │      10 │         0 │
└──────────────┴─────────┴───────┴─────────┴───────────┘
```

**Comment by benfjohnson** [comment]
Is this currently available in the latest npm build? I'm continuing to see errors when trying to use `flow strict`

**Comment by oshimayoan** [comment]
@benfjohnson Unfortunately, from what I see in [here](https://github.com/rpl/flow-coverage-report/commits/v0.5.0) the latest was released on 26th Feb, so they haven't release this yet.

**Comment by rpl** [comment]
@oshimayoan @benfjohnson it has just been released on npm as part of version 0.6.0.

**Pull request merged**
