### PR TITLE
Throttle the number of concurrent `flow coverage $file` calls

### PR DESCRIPTION
**Pull request by ryan953**
`flow coverage` is really fast against the flow server, but with some projects with many (sometimes large) files it can be slow to accumulate all the results which causes flow server to return code `7` and no coverage information. 

This can be fixed by limiting the amount of concurrency that happens as we iterate over all the files. This change aims to batch the number of concurrent promises in groups of five, so we'll shell out 5 times, and only after that coverage data is collected will we start to shell out again. 

Tested against a glob that returns and iterates over 144 files.

### CODE REVIEW

**Comment by rpl** [comment]
@ryan953 I totally agree with the above analysis, I've experienced the same issues by running this report generator on larger projects and I was trying to track down and handle this issues into an experimental branch.

In the experimental branch, I rewrote it from the completely parallel (and pretty naive) Promise.all into a completely "sequential" `async function` and a for loop, so that we don't end up to flood the flow daemon.

I tried the sequential version on a couple of larger projects and it seems to be pretty fast, and so in the initial version in #10 I've not yet introduced any further optimization (nevertheless, I'm open to evaluate further optimizations on this area, e.g. changing the new version to collect coverage data in parallel on a configurable number of files at once)

Could you try the version in #10 on some of your larger project? (I'd like to evaluate how that version perform for you before releasing it as 0.2.0)

**Comment by ryan953** [comment]
@rpl I ran a report on a big flow project and used globs to include only 614 files and timed it. The results were really consistent for each branch.

I checked out this branch and, with the concurrency set to 5. When it can to completion it took between 42.8s and 43.6s. It did fail presumably when `flow coverage` got overwhelmed.

Then I checkout out PR #10 It consistently took between 1m8.5s and 1m9.9s to output the html report.

I ran `time coverage.sh` and my shell script pretty much this:

```
#!/bin/sh
node flow-coverage-report.js \
  -p /data/users/ralbrecht/www-deep \
  -o ~/public_html/coverage-flow/tmp \
  -i 'html/js/**/*.js' \
  -i '... more ... ' \
  -t html
```

**Comment by rpl** [comment]
@ryan953 I've just created #15 to be able to optionally configure a "maximum number" of files to submit to flow at once before waiting for their coverage data.

Can you give it a try on your large project to check if the new "-c" CLI option can give you a similar effect on the time needed to complete the coverage report generation?

**Comment by ryan953** [comment]
@rpl commented directly in #15 

I like the `-c` option with I was missing here, I'll just close this out and run with that new branch which has no conflicts 😄

**Pull request closed without merging**
